name: CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print custom message
        run: |
          echo "Hello from GitHub Actions!"
          echo "Repository name: ${{ github.repository }}"
          echo "Current run number: ${{ github.run_number }}"